api/urls.py
from django.urls import include, path, re_path 
from . import views
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'books', views.BookViewSets, basename='api-books')

urlpatterns = [
    path('', include(router.urls)),
    path('categories/', views.CategoryListAPIView.as_view(), name='api-categories'),
    path('categories/<str:category_slug>/books/', views.BooksByCategoryAPIView.as_view(), name='api-category-books'),
    path('borrowed-books/', views.BorrowedBooksAPIView.as_view(), name='api-borrowed-books'),
    path('borrow/', views.BorrowBookAPIView.as_view(), name='api-borrow-book'),
    path("return/", views.ReturnBookAPIView.as_view(), name="api-return-book"),
    path('auth/', include('djoser.urls')),          
    re_path(r'^auth/', include('djoser.urls.authtoken')),
]

library_system/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls')),
    path('users/', include('users.urls')),
    path('api/', include('api.urls')),
    path('silk/', include('silk.urls', namespace='silk')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views 
from django.contrib.auth import views as auth_views


app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('password-reset/', views.CustomPasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('<str:username>/', views.user_profile, name='user_profile'),
]

library_system/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Digital Library{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'library/css/style.css' %}">
    {% block extra_css %}{% endblock %}
</head>
<body>
    <header>
        <h1>Digital Library</h1>
        <nav>
            <ul>
                <li><a href="{% url 'home' %}">Home</a></li>
                <li><a href="{% url 'categories' %}">Categories</a></li>
                {% if user.is_superuser %}
                <li><a href="{% url 'add_book' %}">Add New Book</a></li>
                {% endif %}
                {% if user.is_authenticated %}
                <li><a href="{% url 'borrowed_books' %}">My Borrowed Books</a></li>
                <li class="user-info">
                    <a href="{% url 'users:user_profile' user.username %}">Hello, <strong>{{ user.username }}</strong></a> | 
                    <form id="logout-form" action="{% url 'users:logout' %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <button type="submit" onclick="return confirmLogout()" style="border: none; background: none; color: white; cursor: pointer;">Logout</button>
                    </form>
                </li>
                {% else %}
                <li><a href="{% url 'users:login' %}">Login</a></li>
                <li><a href="{% url 'users:register' %}">Register</a></li>
                {% endif %}
            </ul>
        </nav>
        
    </header>
    <main>
        {% block content %}
        <!-- Main content will go here -->
        {% endblock %}
    </main>
    <footer>
        <p>Contact us: tadevosyanedgar22@gmail.com | +374-99-33-85-94</p>
    </footer>
    
    <script>
        function confirmLogout() {
            return confirm("Are you sure you want to log out?");
        }
    </script>

    <script>
        document.addEventListener("DOMContentLoaded", function () {
            const carousel = document.querySelector(".carousel");
            if (!carousel) return;  // Exit if there's no carousel on the page

            const prevBtn = document.querySelector(".prev-btn");
            const nextBtn = document.querySelector(".next-btn");

            nextBtn.addEventListener("click", () => {
                carousel.scrollBy({ left: 220, behavior: "smooth" });
            });

            prevBtn.addEventListener("click", () => {
                carousel.scrollBy({ left: -220, behavior: "smooth" });
            });
        });
    </script>
        
</body>
</html>